[tool.poetry]
name = "ou-sphinx-theme"
version = "0.3.0"
description = ""
authors = ["Mark Hall <mark.hall@work.room3b.eu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"

[tool.poetry.plugins."sphinx.html_themes"]
"openuniversity" = "ou_sphinx_theme"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
