[tool.poetry]
name = "fileprep"
version = "0.0.3"
description = "Batch prepare and clean bad formatted excel files for further analysis."
authors = ["Christian Schramm <cschra@gmail.com>"]
license = "GNU Lesser General Public License v3 or later (LGPLv3+)"
readme = "README.md"
homepage = "https://github.com/v0ku/fileprep"
repository = "https://github.com/v0ku/fileprep"
keywords = ["data preparation", "excel"]

[tool.poetry.dependencies]
python = "^3.7"
datetime = "^4.3"
pandas = "^1.0.5"
xlrd = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
