[tool.poetry]
name = "justnow"
version = "0.1.4"
description = "A systemd.timer inspired event parser in pure Python."
authors = ["Bradley Stuart Kirton <bradleykirton@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/BradleyKirton/justnow"
repository = "https://gitlab.com/BradleyKirton/justnow"
keywords = ["systemd.timer", "datetime", "scheduling"]
include = [
  "LICENSE",
  "justnow/justnow.lark"
]
classifiers = [
  "Operating System :: MacOS",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = "^3.8"
lark-parser = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.10.0"
black = "^19.10b0"
isort = "^5.2.2"
flake8 = "^3.8.3"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | libraries
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
